version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 16.x
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm i -f
  build:
     commands:
      - aws s3 cp s3://aim-cicd-1dcfcd7/dev/.env .
      - cat .env
      - chmod +x ./scripts/*.sh
      - echo npm run build
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/node_modules/**/*'
